2024-07-09 13:47:44,402 - root - logging_function.py - ERROR - <module> - Testing saving logs to file.
